camera:
  fps: 30
  optimize_for_speed: true
  preview_quality: low
  resolution:
  - 640
  - 480
gpio:
  button: 6
  led:
    blue: 16
    green: 21
    red: 20
inky:
  color: red
  current_state: tirar_foto
  current_theme: apple_mascot
  dimensions:
  - 250
  - 122
  states:
  - ligado
  - standby
  - desligado
  - tirar_foto
  - tirar_gif
  - erro
paths:
  gifs: ./photos
  photos: ./photos
