version: '3.8'

services:
  cam-server:
    build: .
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/vchiq:/dev/vchiq"
    ports:
      - "5000:5000"
    volumes:
      - ./photos:/app/photos
    restart: unless-stopped
